### ISSUE TITLE
Do not escape audio src path

### ISSUE THREAD

**Issue by GM-Script-Writer-62850** [ltGuillaume/MusicFolderPlayer#1]
https://github.com/ltGuillaume/MusicFolderPlayer/blob/master/music.js#L322
`audio.src = path;//encodeURIComponent(path);`

**Comment by ltGuillaume** [comment]
Does it do any harm then? I have a folder `#` for all artist names starting with numbers or special characters. If I don't use encodeURIComponent, it won't play (it sees it as an anchor, instead of a folder). Of course, I can only replace `#`, but I wasn't sure if any other special chars did the same.

**Comment by ltGuillaume** [comment]
Forward slashes are used on a Windows HTTP server?

**Comment by GM-Script-Writer-62850** [comment]
I am using a apache2 on my linux server: https://imgur.com/a/5CtPA

Did you have any issues with my version working?

**Comment by GM-Script-Writer-62850** [comment]
does using the escape function instead work for you?
`audio.src = escape(path);`

**Comment by ltGuillaume** [comment]
Strange, I thought the behavior of the deprecated `escape()` would mimic `encodeURI()` or `encodeURIComponent()`, but apparently it's a different flavor altogether. `escape()` works just fine over here, so if it also works in your use case, it's the best option. Thanks!

Apart from this, I also need to add a few lines of error handling when playback fails. I just want it to mark the non-played item and continue with the next, since a party player that stops playing instantly becomes a party pooper.

**Comment by GM-Script-Writer-62850** [comment]
`audio.src = encodeURI(path);` also works for me

**Comment by ltGuillaume** [comment]
Not for me in the `#` case, so escape() is best :-)

**Comment by GM-Script-Writer-62850** [comment]
Did you have this issue is my version?

**Comment by ltGuillaume** [comment]
Yeah, I did. Back then, I just added `s.src=file.replace('#', '%23');`.

**Comment by ltGuillaume** [comment]
https://github.com/ltGuillaume/MusicFolderPlayer/commit/b461afcaca3ab8a02cef6128da8528469e66d789

**Comment by GM-Script-Writer-62850** [comment]
- Prevent encoding of `\` in `audio.src` for Apache servers
wrong slash

**Comment by ltGuillaume** [comment]
Lolz, that's odd. I could have sworn I saw actual backslashes when I
checked your post. I didn't understand, that's why I asked whether you were
running a server on Windows, the only theoretical case I could fathom where
backslashes could be used! Anyway, all the more reason I shouldn't code on
a 10" screen, it issues problems that aren't there :-P

Thanks again, escape() seems to be working fine in a few test cases I did.

**Comment by GM-Script-Writer-62850** [comment]
escape seems to break it with some unicode characters, here is one for you to try: 月

**Comment by GM-Script-Writer-62850** [comment]
Using encodeURI seems to to not break anything here
encodeURIComponent is used for parameters like this
'http://example.com/path/to/file?opt='+encodeURIComponent(string)+'&'+encodeURIComponent(string2)`

**Comment by GM-Script-Writer-62850** [comment]
I guess we should use this:
`encodeURI(FILE_PATH).replace(/#/g,'%23');`

**Comment by ltGuillaume** [comment]
And it does work without any escaping? Then I'll just create a function
that replaces `#` with `%23` and go from there (if there are any other
characters that _do_ need escaping.

Thanks so much!

**Comment by GM-Script-Writer-62850** [comment]
Without any escaping as long as there is not a # it works
Using encodeURIComponet break everything, but if you were to unencode `/` it would probably work
Using encodeURI break nothing, works just as well as not escaping
Using escape breaks spacial Unicode characters

encodeURI does tot touch these:
`A-Z a-z 0-9 ; , / ? : @ & = + $ - _ . ! ~ * ' ( ) #`
the only characters that look to break this are # and ?

**Comment by ltGuillaume** [comment]
Wow, that's a thorough investigation. (Probably) definitively fixed in 1.0.2 now :-)

**Comment by GM-Script-Writer-62850** [comment]
`s.replace('#', '%23').replace('?', '%3F');`
but what if there is more than one?
```
function safeURI(src){
   return encodeURI(src).replace(/#/g,'%23').replace(/\?/g,'%3F');
}
```

**Comment by ltGuillaume** [comment]
Dang, I need to get some sleep, not focused at all anymore.,, Either way, I feel using RegExp will inadvertedly introduce a whole new can of worms with RegExp's metacharacters, so simply using `return s.split('#').join('%23').split('?').join('%3F');` is best for this occasion imho. I found my suspicion is documented on StackOverflow, too.

This solution isn't fast, but occurrences will be very limited anyway, so it shouldn't delay the script much at all.

**Comment by GM-Script-Writer-62850** [comment]
StackOverflow link please

**Comment by ltGuillaume** [comment]
https://stackoverflow.com/questions/1144783/how-to-replace-all-occurrences-of-a-string-in-javascript#comment27121391_1144788

Apart from that, I genuinely hate RegExp, because I keep being awed by its power while stunned and frustrated by its pickyness and lack of intuitiveness :-P

**Comment by GM-Script-Writer-62850** [comment]
Knew there was a way to only use replace once
```
function safeURI(src){
   return encodeURI(src).replace(/[(#\?]/g,function(char){return escape(char);});
}
```

**Comment by ltGuillaume** [comment]
Cool! And using encodeURI() just to be on the safe side?

Just tried your updated project, looks awesome! Tabbed interface is nice.
It's working great in Vivaldi (Chrome), but in Waterfox I get the error
"config is null" with a reference to the line where you check if config is
undefined. Script stops and nothing works.

**Comment by GM-Script-Writer-62850** [comment]
encodeURI is to be on the safe side
encodeURI is intended to encode a entire url, it does not target ?, =, &, and # as these special url chars
? is used to send parameters to a server
= is used to separate parameters names from values
& is used to separate separate parameters
# is used for scrolling to elements on a page based on element IDs
I think we could escape both = and &, but browsers know if there has not been a ? symbol they are not being used for parameters
`function safeURI(src){return encodeURI(src).replace(/[(\?=&#]/g,function(char){return escape(char);});}`
In theory we should be able to use encode uri component and unescape every / if we do not want to escape a few more chars our self
`function safeURI(src){return encodeURIComponent(src).replace(/%2F/g,'/');}`
if this is used on a full link you need to decode : also

**Comment by GM-Script-Writer-62850** [comment]
config is null; easy fix; only need to add 4 chars

**Comment by ltGuillaume** [comment]
True, but there wasn't any in Vivaldi either.

**Comment by GM-Script-Writer-62850** [comment]
firefox should behave the same, the only way for it not to is if the config option has not been set

it a very inconvenient to debug that part as it is set to save the config on page leave, so even if you clear it then reload it saves it and you do not get a cleran config

if you used the same config name i did in your version on the same server both pages share the same config data, if you used Vivaldi on your project then loaded mine on the same server you had a exist config that was not null

**Comment by ltGuillaume** [comment]
I waited for Cookies Exterminator to clean up cookies & LS, but I guess it didn't take those instances. Sorry to have misinformed you.
