### ISSUE TITLE
Display Music File Type

### ISSUE THREAD

**Issue by xRadio-us** [ltGuillaume/MusicFolderPlayer#10]
Most people do not need to see whether the music file is MP3, OGG or WAV. However, that is important to me. I am currently evaluating and comparing audio pronunciation clips in several formats to add to a test web site [Time-Place-Pronounce](https://xradio.us/start/tmf.html) that I am developing.

Since your music.php results show the file extension, I assume that this can be modified somewhere in your music.js file. Maybe you can point to where I can make code changes.

If you add this feature, one could either display the extension type or colorize the filename depending on the audio file type.

**Comment by ltGuillaume** [comment]
Sure! In music.js, search for
```
function getSong(path) {
	return path.substring(path.lastIndexOf('/') + 1, path.lastIndexOf('.'));
}
```

and replace it with
```
function getSong(path) {
	return path.substring(path.lastIndexOf('/') + 1);
}
```

That's all!

**Comment by xRadio-us** [comment]
I decided to only display the extension fo non-MP3 files (M4A, OGG, WAV, etc.).

```
function getSong(path) {
    var x    = path.lastIndexOf('.');
    var ext  = path.substring(x).toLowerCase(); 
    var name = path.substring(path.lastIndexOf('/') + 1,x);
    if(ext != '.mp3') name += ext.replace('.',' . ');
    return name;
}
```

**Comment by xRadio-us** [comment]
I updated this to replace WAV, OGG and M4A with raised html entity symbols. Unfortunately, I had to cut and paste the actual raised W, degree, and raised 4 symbols since &#999; style was not decoded.

``if(ext != '.mp3') name += ext.replace('.wav',' ᵂ').replace('.ogg',' °').replace('m4a','⁴');``

**Comment by ltGuillaume** [comment]
Well, if it works, it works ;-)
