### ISSUE TITLE
Horizontal Display of Filenames Option

### ISSUE THREAD

**Issue by xRadio-us** [ltGuillaume/MusicFolderPlayer#11]
For music files, many with long names, vertical display of filenames is okay. However, for the short audio filenames that I tend to use for development, it is very inconvenient. A horizontal filename display option would show many more files in a much smaller space allowing for quicker direct click access without a lot of unnecessary scrolling.

**Comment by ltGuillaume** [comment]
Yes, I see where you're coming from. The easiest way is to just add the following CSS to `music.css` or `musictheme.css` (update `music.htm` to the last commit's version for that)

```
#tree li.song {
	display: inline-block;
	margin-right: 2em;
}
```

Would that suffice?

**Comment by xRadio-us** [comment]
Thanks, That works well in **DIV:library** while not affecting **DIV:playlist**. I will probably want to turn this into a **CSS .horizontal CLASS** so that I can turn it on and off.

One thing that I noticed is that playing a file in **DIV:library** automatically adds it to **DIV:playlist** which is distracting visually. It drops my horizontal files display in **DIV:library** further down the screen.

Since I added my **MODE: ALL-or-ONE** button switch, I think that I will try to make **DIV:playlist** hidden when I select **MODE: ONE**.  I also may want to keep my new **CSS class .horizontal** set to *OFF* in **MODE: ALL** and set to *ON* in **MODE:ONE**.

Any thoughts/suggestions/code to accomplish any of this would be welcome. Again, thanks for your help.

**Comment by ltGuillaume** [comment]
- If you don't wan't the playlist height to automatically change, simply add this:
musictheme.css: `#playlist { height: 7.75em !important }`
- To remove it completely when using MODE: ONE, you could just use
music.css: `#playlist.one { display: none !important }`
and set the className via
music.js: `dom.playlist = 'one';`

**Comment by xRadio-us** [comment]
I renamed my mode toggle - MUSIC Mode (default) or FILES Mode. Playlist DIV is hidden in FILES Mode..
```
function setMode() { document.getElementById('playlistdiv').style.display=(fMode)?"none":"block";}

<button id="playMode" onclick="this.innerHTML=(fMode=!fMode)?filesMode:musicMode;setMode();">
```

**Comment by ltGuillaume** [comment]
I like the toggle `(fMode=!fMode)`, I should use that as well.
