### ISSUE TITLE
Dark Theme for Night Owls

### ISSUE THREAD

**Issue by xRadio-us** [ltGuillaume/MusicFolderPlayer#12]
re: [Dark Audio Player Readme + Example](https://xradio.us/start/dap/readme-darkly.html)

Like many developers, I do my coding and testing most often at night. While your Music Folder Player project is useful, the default theme is unusable for Night Owls. I also have little use for "party" features like Random Play and Crossfade.

I might suggest that you host a second Night Owl or Developers Version. You can use my code modifications as base code. My [Dark Theme Version](https://xradio.us/start/dap/) has disabled Crossfade and Random Play. I added a Mode button toggle to choose between continuous and single play.

For any second version, I hope that you will add some sort of display of audio file type and an option for horizontal display of file links.

**Comment by ltGuillaume** [comment]
@xRadio-us Please check out https://github.com/ltGuillaume/MusicFolderPlayer/commit/9fb00d0e4c2da768d7b261fcd55b740a12b2cd7e and report back to me.

**Comment by ltGuillaume** [comment]
@xRadio-us and nice to see the adjustments you've made, looks completely different! :-)

**Comment by xRadio-us** [comment]
I will take a look a bit later at your updated music*.* files to see how your Dark Theme option looks/behaves.

Since I renamed my files to audio*.* there should be no conflict.

**Comment by ltGuillaume** [comment]
![mfp-dark](https://user-images.githubusercontent.com/4777345/53241327-a3f6b600-36a1-11e9-9628-b40521ccf445.png)
![mfp-darksnow](https://user-images.githubusercontent.com/4777345/53241328-a48f4c80-36a1-11e9-8e71-a53cdbb347c9.png)

**Comment by xRadio-us** [comment]
Your new [musictheme.css](https://github.com/ltGuillaume/MusicFolderPlayer/blob/master/musictheme.css) (Dark Theme) addition seems like a good basic quick-fix for a lot of folks, especially for phones and tablets.

I will have to experiment on other projects with your **CSS filter: invert** method.

**Comment by ltGuillaume** [comment]
I was pleasantly surprised by the results (also that it automatically took care of the scrollbar colors), but it's not perfect: although there's no issue on mobile devices afaik, for Windows (probably due to ClearType?), I added the much-used 'hack' `text-shadow: -.0000001px 0 0 #aaa` to make the font less thin and harsh.
