### ISSUE TITLE
Mp3 files not playing...?

### ISSUE THREAD

**Issue by OoLunar** [ltGuillaume/MusicFolderPlayer#15]
First off, wonderful app you've built. I love every piece of it, except for my issue.

Let me just say it's easier to explain if you go take a look yourself. 
https://forsaken-borders.net/media/music/music.htm
When I go to play my mp3 files, the song title goes red, and skips to the next, then repeats. Not quite sure what's causing this, or even how to see the errors through the console. I've restarted the Apache2 service a few times, nothing. The directories seem right, and I don't think I edited any of the files wrongly (other than replacing the default image), however feel free to take a look yourself by going to the url:
https://forsaken-borders.net/media/music
and seeing what could be wrong. I have recently (four hours ago) installed the latest commitment, so it might just be a bug. Who knows?

Anyways, thank you for all your hard work, and please keep it up!
        - Lunar, Owner of ForSaken Borders

**Comment by OoLunar** [comment]
Looked at https://github.com/ltGuillaume/MusicFolderPlayer/issues/1, and saw that I should create a symlink, which is exactly what I did. Sorry for not looking earlier. Thank you for all that you've done though!

**Comment by ltGuillaume** [comment]
Issue #4 is why I included the easiest method (create a symlink) in the [Wiki](../wiki), too. It's pretty much exactly what you went through ;-)

Cheers!
