### ISSUE TITLE
REQUEST: How do we implement media session notifications for mobile?

### ISSUE THREAD

**Issue by OoLunar** [ltGuillaume/MusicFolderPlayer#16]
Hello! Recently, I'm developing an app that's basically just a really big iframe to your music player, and  when the users leave the app, all they get to control from the notification bar is just pause/play. I was wondering what and where I could implement media session controller (see [here](https://developers.google.com/web/updates/2017/02/media-session) for what I mean). I currently have something along the lines of

`navigator.mediaSession.setActionHandler('playpause()', function() {});
navigator.mediaSession.setActionHandler('playpause()', function() {});
navigator.mediaSession.setActionHandler('previous()', function() {});
navigator.mediaSession.setActionHandler('nextBtn()', function() {});`

but I know that's just plain wrong. Any ideas?

**Comment by ltGuillaume** [comment]
For starters, this should probably do it:

```
navigator.mediaSession.setActionHandler('play', playPause); navigator.mediaSession.setActionHandler('pause', playPause); navigator.mediaSession.setActionHandler('previoustrack', previous); navigator.mediaSession.setActionHandler('nexttrack', nextBtn);
```

At the end of the function `play(index)`, you could try adding:
```
if ('mediaSession' in navigator) {
	navigator.mediaSession.metadata = new MediaMetadata({
		title: getSong(path),
		artist: getArtist(path),
		artwork: [ { src: c } ]
	}
```

Disclaimer: I just read https://developers.google.com/web/updates/2017/02/media-session, I haven't tested anything, that's up to you now :-) Good luck and please keep me posted on your progress!

**Comment by OoLunar** [comment]
Awesome! Testing now

**Comment by OoLunar** [comment]
Nothing. Knowing me, I probably put it in the wrong place. However something I did notice is that on my very puny web code editor, it marked "mediaSession" in red.

**Comment by OoLunar** [comment]
I red it wrong, the code is expecting a comma somewhere, not the end of a statement

**Comment by OoLunar** [comment]
Fixed the typo. Unfortunately it doesn't work. New feature maybe? xD

**Comment by ltGuillaume** [comment]
```
	if ('mediaSession' in navigator) {
		navigator.mediaSession.setActionHandler('previoustrack', previous);
		navigator.mediaSession.setActionHandler('nexttrack', nextBtn);
		navigator.mediaSession.metadata = new MediaMetadata();
	}
```
in `init()` works just fine.

And even though the fields are set properly with the following code in `play(index)`, it doesn't show up somehow.
```
	if ('mediaSession' in navigator) {
		navigator.mediaSession.metadata.title =  getSong(path);
		navigator.mediaSession.metadata.artist = getArtist(path);
		navigator.mediaSession.metadata.artwork = [ { src: c } ];
	}
```

**Comment by ltGuillaume** [comment]
Oh wait, it DID work! It was just that I used an Incognito tab. When you don't use an incognito tab, it does work nicely. I've implemented it in the latest commit. You can see the code changes here: https://github.com/ltGuillaume/MusicFolderPlayer/commit/a70724302ed555bd22d90352895025debe58d0fd

**Comment by OoLunar** [comment]
Awesome! Glad you can do that! Currently my app is using Custom Chrome Tabs, so I don't see any issues of why is wouldn't work. Either way, thanks man!

**Comment by ltGuillaume** [comment]
Will your app be open-source?

**Comment by ltGuillaume** [comment]
@OoLunar how's the Android app coming along?

**Comment by OoLunar** [comment]
Here it is:
https://forsaken-borders.net/apps

It's honestly just a Iframe to my website xD, uses Chrome Custom Tabs

**Comment by ltGuillaume** [comment]
Cool, thx! I took a look at the code, looks clean, I may dive into this custom tabs feature later on.

**Comment by OoLunar** [comment]
Glad you like it. One thing that you can note about me, is that I will _always_ try to make my code clean. Another thing you can note about me is that half my code comes from Google, which means there is always room for improvement. If you have any suggestions of why and what is there, please do ask!
