### ISSUE TITLE
Disable Randomize play

### ISSUE THREAD

**Issue by JARVIS-AI** [ltGuillaume/MusicFolderPlayer#21]
Hi
How can I disable randomize the play ?
With disabled random button still player choose a random music in entire folder and play it 

This is unexpected

Browser : Chrome Firefox Vivaldi (No matter)
Thanks in advance

**Comment by JARVIS-AI** [comment]
Never mind 

It was in :
``Playlist >> Continue from library``

Anyone has this one set just ``Clear cookie of webpage`` To reset web apps

Thanks for great software

**Comment by ltGuillaume** [comment]
The Randomize button does what it says:
![image](https://user-images.githubusercontent.com/4777345/61323034-4b21e880-a80f-11e9-85d5-c0863ffbd0b9.png)

What you're actually after can be found here:
![image](https://user-images.githubusercontent.com/4777345/61323095-74db0f80-a80f-11e9-97d4-4dd8d3e3cb4b.png)
where you can set:
![image](https://user-images.githubusercontent.com/4777345/61323130-858b8580-a80f-11e9-9415-c65cdf6a93ef.png)
(the default setting is "Random from library").
