### ISSUE TITLE
Player doesn't appear in desktop browser

### ISSUE THREAD

**Issue by mathieudupre** [ltGuillaume/MusicFolderPlayer#22]
Hi,

I'm stuck with a dark screen and the icon in the middle of the page with chrome and firefox. I may clic anywhere, nothing happens.

But with my android device, the player appears when I touch the middle icon. But the player seems to not find my songs.

I've checked the permissions in my server, I've modified it, useless.
I've checked the file music.php and  $root is link to library directory, which directory I've created in the root folder and where I've put my songs.
I've also checked the songs files names to make them without space or anything else strange.

So I'm stucked! Did I forget something? Thanks for your help.
Mathieu

**Comment by ltGuillaume** [comment]
Please press F12 and check for messages in the browser console.

**Comment by mathieudupre** [comment]
Thanks for your fast answer!

When I say "root folder" I'm talking about the MusicFolderPlayer folder and not the root of the server folder. So its location is ~/Public_html/Music/.

What should I check in the browser console? I'm familiar with html and old css, but just have few hints about php.

**Comment by mathieudupre** [comment]
Yes, the music.* files are in the same folder with my "library" folder

**Comment by mathieudupre** [comment]
oh, I forgot, here is the link:
http://neotango.fr/music/

**Comment by ltGuillaume** [comment]
It says there is no http://neotango.fr/music/music.php

**Comment by mathieudupre** [comment]
Oh, yes, maybe something in the .htaccess that blocks the file? I got check that

**Comment by mathieudupre** [comment]
I've put the music folder side by side with a drupal installation. It looks like it blocks the cache for php files.

**Comment by ltGuillaume** [comment]
Yeah that may also cause it: it'll block other .php files to prevent malicious code from running.

**Comment by mathieudupre** [comment]
So do you think I may use musicfolderplayer in this directory? Is there a trick to make it works without compromising security in my drupal website?

**Comment by mathieudupre** [comment]
I've tried in a different server and it comes out with internal server!
http://lasorbonne.net/music/

**Comment by ltGuillaume** [comment]
And what do your server error logs say?

Or, see https://stackoverflow.com/questions/17693391/500-internal-server-error-for-php-file-not-for-html

**Comment by mathieudupre** [comment]
It seems the issue comes from permissions. I've set everything to 755 and it woks well now!
If you want to listen to tango music:
http://lasorbonne.net/music/

Thanks again for your help and for your great job! ;)
