### ISSUE TITLE
Album art question

### ISSUE THREAD

**Issue by jranma** [ltGuillaume/MusicFolderPlayer#23]
I don't understand how the image is displayed. 
Is there only one image per folder (say, per album), or does each song have its own image? If so, how is it discovered? With the same name as the mp3 file? 
cheers, thanks for nice player

**Comment by ltGuillaume** [comment]
It's folder-based. It shows jpg and png files, giving preference to cover.jpg or cover.png.

This is rudimentary, I know. How are your cover images organized?

**Comment by jranma** [comment]
folder/musicXXX.mp3
folder/musicXXX.png
folder/musicYYY.mp3
folder/musicYYY.png

it would be cool to display the png according to mp3 played :)

**Comment by ltGuillaume** [comment]
Please try https://github.com/ltGuillaume/MusicFolderPlayer/tree/auth-logout-button
