### ISSUE TITLE
Incompatible with Webview-based Android browsers?

### ISSUE THREAD

**Issue by xRadio-us** [ltGuillaume/MusicFolderPlayer#25]
My modified dark theme MFP https://1-dot.com/audio/player seems to work well with Windows browsers. However, on my Android TV box, Microsoft's Edge browser produces no sound. (BTW, the Windows Edge Chromium Beta works well,)

A more significant problem is that my MFP does a blue-screen freeze when started from a "Webview"-based browser such Lightning, Hermit, the default Android browser and many others.

I wanted to stop running my MFP when this happens to explain the problem to the browser user. In JavaScript, Webview should be detected by searching for ";wv" in variable navigator.userAgent. However, this did not work. A quick Google search indicated that I instead had to detect this on the SERVER SIDE using PHP.

So, I tried to insert detection code into my audio.php file. The detection worked but I still got the blue-screen freeze with Webview-based browsers. To get around this problem (successfully), I renamed by index.html to index.php and then inserted the following PHP code at the top.

```
<?php $wv = $_SERVER["HTTP_X_REQUESTED_WITH"];
if(strlen($wv) > 0) { 
echo "<H2>[ ",$wv," ] - incompatible Android 'Webview' browser.</H2>";
echo "<H3>For Android, we recommend Brave, Chrome, or Firefox.<br><br>";
echo "[ <a href='/'>Return to 1-dot.com homepage</a> ]</H3>\r\n\n";
exit();
}
?>

**Comment by ltGuillaume** [comment]
I've been using MFP on WebView browsers, I'm afraid this is a very very specific problem that you seem to have generalized to all WebView browsers. In order to get to the bottom of this:

1) Please see if the same happens with an MFP instance straight from this repository (without modifications)
2) On what phone(s)/tablet(s), with which Android version did you experience this? Has WebView been updated to the latest version via the Play Store?

**Comment by xRadio-us** [comment]
I tested my modded MFP wirh a few Webview-based browsers on an Android TV box (Amlogic S912 SoC). However, subsequent testing of the Lightning browser (same APK file) on a recent Android phone did not show similar freezing behavior.

So, I will probably have to find a way to more narrowly target this problem detection. For now, I am defaulting my MFP back to a non-detecting HTML file instead of PHP. However, feedback would be helpful from other MFP users using a Webview-based browser on an Android TV box. Does my MFP https://1-dot.com/audio/player lock up or load normally? If it locks up, please let me know which Android TV box model you use and which Webview-based browser you use.

I updated my backup (detecting) https://1-dot.com/audio/player/i.php code to work better with both phone and TV box.

```
<?php $wv = $_SERVER["HTTP_X_REQUESTED_WITH"];
if(strlen($wv) > 0) { 
  echo "<style>html,body{font-size:1.7em;background:#103060;color:white}";
  echo "a{color:palegreen;text-decoration:none}</style>";
  echo "[ ",$wv," ]\r\n\n";
  echo "<P>Android 'Webview' browser\r\n\n";
  echo "</P><P>Try (Android) Brave, Chrome or Firefox.\r\n\n";
  echo "</P><center><a href='/'>[ 1-dot.com ]</a></center>\r\n\n";
  exit();
}
?>
```

**Comment by ltGuillaume** [comment]
I just tested your instance on 1-dot.com on an Android 8.1.0 and an 9.0 (LineageOS) phone in Lightning Browser (installed from F-Droid): I couldn't find any playback or freeze issues.

I don't own an Android TV device, so I can't help you test there. It might be buggy software, though, those Android TV devices are known for it.

**Comment by ltGuillaume** [comment]
Have you tried using a browser on those devices that allows for USB debugging, such as Firefox and Chrome? See https://developer.mozilla.org/en-US/docs/Tools/Remote_Debugging/Debugging_Firefox_for_Android_with_WebIDE and https://developers.google.com/web/tools/chrome-devtools/remote-debugging

You also might find some clues by checking Logcat.

**Comment by xRadio-us** [comment]
Thanks for the links but, frankly, the relatively small number of Android TV box users using a Webview-based browser when visiting my customized MFP page is not worth further effort.

My MFP version works well enough with Windows, Linux, iOS, and Android phones and also non-Webview Android TV box browsers. This 1% problem is just very low priority.
