### ISSUE TITLE
Option to save playlist position on the server.

### ISSUE THREAD

**Issue by katrikm** [ltGuillaume/MusicFolderPlayer#27]
Hello. Would it be possible to save online playlist position on the server? 
It would be great to have the option to continue playlist on different device (or browser).
Thanks.

**Comment by ltGuillaume** [comment]
I might add this in the future, thanks.

**Comment by ltGuillaume** [comment]
@katrikm I've just implemented the feature in https://github.com/ltGuillaume/MusicFolderPlayer/commit/4ae05762570ce1ae3d341fc706745f483517d86a

**Comment by ltGuillaume** [comment]
Earth to @katrikm

**Comment by ltGuillaume** [comment]
I'm closing this issue, since @katrikm apparently has lost interest.
