### ISSUE TITLE
Root is not defined

### ISSUE THREAD

**Issue by Chuck217** [ltGuillaume/MusicFolderPlayer#28]
I am in the process of adding my music folders into /MusicFolderPlayer/library 

I have gotten to a point, where one of my folders of music is causing an error 

ReferenceError: root is not defined music.js:547:3
    fillShare http://www.mydomain/MusicFolderPlayer/music.js:547
    buildPlaylist http://www.mydomain/MusicFolderPlayer/music.js:435
    onload http://www.mydomain/MusicFolderPlayer/music.js:159

I am guessing this is a problem with my mp3 files, or permissions of those mp3s?   Any guidance on how I can determine what is throwing the error?

This is on a shared webhost,   I have another copy of MFP running on XAMPP on Windows,  using the same music folder structure, and it works fine,  with 193,000 mp3s   My website version has only 19,500 ..

I've isolated the folder in question to an mp3 .. but the naming is just like the rest .. Would love to chat about where this problem is coming from -- I know its on my end somewhere

Thanks
Chuck

**Comment by ltGuillaume** [comment]
Can you please look at the output of http://www.mydomain/MusicFolderPlayer/music.php ?

**Comment by Chuck217** [comment]
I am unsure if I have access to that on my host, but I am in the process of checking .. If I go to music.php with the problem file in question in place .. I get 

var root="library/"; var library=

If I delete the mp3 in question ... I get 

var root="library/"; var library={"01-January":{"2020-01-02 Basket Of Cheer":{"\/":{"0128 - Acdc -Shoot To Thrill.mp3":"","0129 - Jimmy H -Johnny B. 

I can happily share with you my URL in question privately

**Comment by Chuck217** [comment]
Also -- the problem mp3,  plays and loads just fine on my Windows / XAMPP test install .. just not on my shared host

**Comment by ltGuillaume** [comment]
It's probably the name of the file. Can you share the _exact_ full filename here?

**Comment by Chuck217** [comment]
0001 - Kíla - Gwerzy.mp3    -- HA .. I see it ..  disregard ..

**Comment by ltGuillaume** [comment]
The `í` shouldn't be a problem, though. I copied a file with that exact name to my MFP instance, no problemo.

But from you response I take it that taking out the `í` _did_ fix it? In that case, it's probably something with the codepage settings on your server. I'm not sure how to fix that, though...

**Comment by Chuck217** [comment]
Ok Thanks -- I appreciate the time!

**Comment by ltGuillaume** [comment]
Oh, and by the way, I did see the difference between `i` and `í` with the default font pretty clearly, I think it's just that you didn't know what to look for just yet. Otherwise, just rename the file `musictxt.woff` (and `musictxtsc.woff` for touch screens) and see if it's better.
