### ISSUE TITLE
Logo Design for Music Folder Player

### ISSUE THREAD

**Issue by zuuritaly** [ltGuillaume/MusicFolderPlayer#3]
Hello!

I'm a graphic designer and I like to support open source projects. I would like to design a logo for your project if you interested, I will be happy to work with you! :)

Best Regards

Zuur

Graphic Designer

**Comment by ltGuillaume** [comment]
Hey Zuur! Thx for contacting me, sry I wasn't able to respond sooner. As of yet, I don't think this project really needs a logo or anything, but thanks for the offer. Cheers!

**Comment by ltGuillaume** [comment]
Hey @zuuritaly! Thx for contacting me, sry I wasn't able to respond sooner. As of yet, I don't think this project really needs a logo or anything, but thanks for the offer. Cheers!
