### ISSUE TITLE
Playlist box length

### ISSUE THREAD

**Issue by zdarin** [ltGuillaume/MusicFolderPlayer#34]
In playlist box length seam to long can you fix like in folders box length or some another way not to wrap text maybe some sliding text on mobile on both playlist and folder?
How you think?

![IMG_B32EEF97FC11-1](https://user-images.githubusercontent.com/42121280/89128030-2a503200-d4fb-11ea-87a4-fda7e0a3fb4f.jpeg)

**Comment by ltGuillaume** [comment]
You mean the width (so, horizontal length), right? I did this on purpose, so that the playlist items wouldn't take up more space vertically (which also looked really bad). I think it's fine that you can scroll horizontally. What's the reason you you'd like to see this differently?

**Comment by zdarin** [comment]
Yes width horizontal length.
Because on mobile scroll some times like this: all box scrolling to left bottom or right to top some thing like that if you understand it will be better you to try on yourself.

And buttons i think little bit can be larger for mobile and maybe for desktop

**Comment by ltGuillaume** [comment]
I'm sorry, I'm not sure what you mean by "all box scrolling to left bottom or right to top some thing like that". Could you perhaps rephrase, or show me with a screenshot/recording what you mean?

**Comment by zdarin** [comment]
sorry not mentioned that which song name to long can this show up


[RPReplay_Final1596394195.MP4.zip](https://github.com/ltGuillaume/MusicFolderPlayer/files/5012644/RPReplay_Final1596394195.MP4.zip)

**Comment by ltGuillaume** [comment]
Ah yes, I understand. I still think it's the best way to present the playlist, and you can easily teach yourself to scroll a bit from left to right as well, so you prevent this behavior. It's also dependent on the browser you use. For example, the new Firefox detects which direction you want to be scrolling in (horizontally or vertically) much better.

But if you'd like to disable horizontal scrolling completely, you can simply removing the following from `music.css`:
```
	html.touch #playlist {
		overflow-x: auto;
		white-space: nowrap;
	}
```

**Comment by ltGuillaume** [comment]
Also, it's too bad that your language doesn't seem to be supported by the font I'm using... 😒

**Comment by zdarin** [comment]
but language font almost good :) yes i know that scroll ok but some time touch not right way and its scroll not where should 
i think best solution and fast that will be as folder shows (song name title wrapped) to two line and its good on mobile

**Comment by ltGuillaume** [comment]
No that would require too much vertical space per song, it's not what I want. But as I said, you can easily change it for yourself by just removing those lines from `music.css`.

As for the font, you might just try to rename or remove musictxt.woff and `musictxtsc.woff` and see if you like the default sans-serif fonts your OS apply to it.
