### ISSUE TITLE
Trying to Play a Song Makes it just Cycle through the whole Library?

### ISSUE THREAD

**Issue by callowaysutton** [ltGuillaume/MusicFolderPlayer#4]
I installed it and configured it to my Music Library but all it does it skip the song and go to the next one then skipping that one.

Right now I'm running Xampp on Windows 10 64 Bit

**Comment by ltGuillaume** [comment]
@callowaysutton Please check the value you've set for the variable `$root` in music.php. I'm guessing you've set it to an absolute path, such as `D:\User\Music`. It must be accessible directly through the web server and relative to the path of music.*

The easiest way is to simply leave the default value (`$root = 'library';`) and create a symlink inside the folder of the music.* files to your music folder.
Example: `mklink /d D:\xampp\htdocs\music\library D:\User\Music`

**Comment by callowaysutton** [comment]
Yes it works perfectly now, thank you!

**Comment by ltGuillaume** [comment]
@callowaysutton Made quite a few changes lately, so be advised ;-)
