### ISSUE TITLE
Album art

### ISSUE THREAD

**Issue by Armand95** [ltGuillaume/MusicFolderPlayer#42]
Hi, I wonder if you can do something to get the music album art directly from the mp3 tags ? I know theres existing librairies in JS and php to do that and that'll be much easier than to extract all music's album art.. I hope you can do that ! And by the way I really love your player 👍

**Comment by Armand95** [comment]
I juste rewrote the code and it worked so no worry !

**Comment by ltGuillaume** [comment]
Cool! Could you share the code changes? Perhaps I will some day consider optional implementing local metadata extraction.

**Comment by Armand95** [comment]
Sure!  how can I share the file ?

**Comment by ltGuillaume** [comment]
You can just share it here after you ZIP/GZ it.

**Comment by Armand95** [comment]
Okay so, I used the jsmediatags library to make it work and attached <script src="jsmediatags.min.js"></script> in music.html And I also changed it to make the music cover be the website icon
(The changes are in playNext function)
[music.js.zip](https://github.com/ltGuillaume/MusicFolderPlayer/files/5452148/music.js.zip)
[jsmediatags.min.js.zip](https://github.com/ltGuillaume/MusicFolderPlayer/files/5452151/jsmediatags.min.js.zip)

**Comment by ltGuillaume** [comment]
Looks good, one question though: are you sure that using `jsmediatags.read()` like this doesn't download the file _twice_ (once for playback and once for the cover extraction)? I guess you can check in the Network tab of your browser console if the network request is made twice or whether the browser cache is used.

> I juste have one bug at the moment and I think its because of my changes, its that the artists with numbers being first in their name, the numbers aren't displaying in the title in the player.

Did it work without your changes?

**Comment by Armand95** [comment]
I just checked and its only downloading the file one time.
![image](https://user-images.githubusercontent.com/36240824/97445959-22533300-192e-11eb-82f7-2163c48b91b4.png)

I also tried with a fresh restart with the master branch and its working for the artist name

**Comment by ltGuillaume** [comment]
I suppose there's some (syntax) error that cuts off JavaScript execution then, because your code doesn't directly influence the `dom.album`.

**Comment by Armand95** [comment]
I'll look into it this evening! Thanks for the help

**Comment by ltGuillaume** [comment]
@Armand95 Any news on this?

**Comment by Armand95** [comment]
Yup! I checked it last time and the bug was originaly here on your code so i just rewrote the code tu use id3 tags for the name, album, artist.. And it works very well now ! The code is also very inefficient but it works 🤷🏻‍♂️

**Comment by ltGuillaume** [comment]
It's been a while, so I don't remember the specifics, but if youbsay the bug's in my code, is there a chance people will run into it when they don't use your changes? If so, I'd like to fix it 😁

**Comment by Armand95** [comment]
I just downloaded a new copy of the player and put my songs to test it and the bug's still here. You can try yourself with artists that starts with a number (In my case its 2TH or 47ter ... (French artists)).
![image](https://user-images.githubusercontent.com/36240824/99420877-096ee980-28fe-11eb-846a-4761c98eed96.png)
As you can see on the screenshot, the numbers aren't displaying in the music's title 🤷🏻‍♂️
But I don't really know how to fix it... You could use ID3 tags like I did but you'll have to rewrote a lot of the code. Sorry 😬
Oh and btw, your code isn't compatible with ssl (https) ! 🙂

**Comment by ltGuillaume** [comment]
So what's the exact filename in this case?

**Comment by Armand95** [comment]
![image](https://user-images.githubusercontent.com/36240824/99429052-c0239780-2907-11eb-9dab-7f4e58c79eb0.png)
Here's the full page, and the filename for exemple is "2TH - Bae.mp3"

**Comment by ltGuillaume** [comment]
Thx I'll have a look at it!
