### ISSUE TITLE
music.ini library configure

### ISSUE THREAD

**Issue by zdarin** [ltGuillaume/MusicFolderPlayer#43]
Hi i tried to configure music.ini and place path to music folder, but player only show folders and can't play music.
Using macOS. And also if make alias can't recognise path

**Comment by ltGuillaume** [comment]
Hi!

Did you set the path _relative to the music.ini file_ or did you set an absolute path?

If a symbolic link to another path doesn't work, then perhaps user PHP runs under doesn't have read permissions for that folder, or PHP itself lacks the permission to access that path (set the `open_basedir` PHP value).

**Comment by zdarin** [comment]
Path is absolute, but its out of web server folder of musicfolderplayer. I think its permissions

**Comment by ltGuillaume** [comment]
The path cannot be absolute, so you'd need to use a symbolic link either way. Then check whether adding the permissions are ok for the linked-to directory (can the user under which PHP runs read this directory?). If that's not enough, try adding the absolute path of the linked-to directory to the PHP value `open_basedir`).

**Comment by zdarin** [comment]
Yes symbolic link worked thx for help

**Comment by ltGuillaume** [comment]
No problem! Cheers!

**Comment by ltGuillaume** [comment]
Did you need to change the PHP value `open_basedir`?

**Comment by zdarin** [comment]
No, only simbolic link make tested and worked

**Comment by ltGuillaume** [comment]
Great! Thx for the feedback, will come in handy when others have a similar issue.

**Comment by zdarin** [comment]
;) if need some tests on macos can write
