### ISSUE TITLE
Random play 

### ISSUE THREAD

**Issue by zdarin** [ltGuillaume/MusicFolderPlayer#44]
When songs end it play random song from another folder, but no check for Random play

**Comment by ltGuillaume** [comment]
Playlist -> After playlist

**Comment by zdarin** [comment]
all ok sorry thx for understanding

**Comment by zdarin** [comment]
Can i ask one more question can library folders be changed view from a-z to z-a, becouse now i have folder named by year.month.day i would like to wiev 2020 year folders in top but now i see oldest folders

**Comment by ltGuillaume** [comment]
https://github.com/ltGuillaume/MusicFolderPlayer/blob/3eec5fc9edbf2db60c8c473cbc998e3ba5a821eb/music.php#L104

If you change that to
```
		$scan = scandir($dir, 1);
```

the order will be Z-A.

**Comment by zdarin** [comment]
thx now all good, Best Player
