### ISSUE TITLE
black screen 

### ISSUE THREAD

**Issue by jranma** [ltGuillaume/MusicFolderPlayer#46]
Hello 
After a fresh install, I only get a blank (black) screen. using F12, I see this error message: 
Uncaught ReferenceError: s_nopathexp is not defined
    at HTMLScriptElement.lib.onload (music.js:99)

**Comment by ltGuillaume** [comment]
You'll need to have a PHP environment running for MFP to work.

**Comment by jranma** [comment]
well done ! 
parse_ini_file() was disabled using disable_functions...

**Comment by ltGuillaume** [comment]
Ah that's good to know! Is it common that `parse_ini_file()` is disabled? In that case, I'll add a comment about it in the Wiki.

**Comment by jranma** [comment]
well... it could be common with paranoid people like me...
this function should probably not be disabled, I just copy-pasted some list and didn't notice this setting...  :)

**Comment by ltGuillaume** [comment]
Ok, that makes sense. I'm guessing if there aren't any defaults for this, it would make sense that people who adopt such a list to disable functions already go through the used functions in new pieces of software they'd like to run. No need to complicate my instructions then.
