### ISSUE TITLE
ID3 tags

### ISSUE THREAD

**Issue by Invictaz** [ltGuillaume/MusicFolderPlayer#5]
In your screenshot example, ID3 tags and/or track titles and artist names are shown.
How to enable this? 

It now only reads filename (without extension)

**Comment by ltGuillaume** [comment]
See the Wiki: https://github.com/ltGuillaume/MusicFolderPlayer/wiki

**Comment by Invictaz** [comment]
@ltGuillaume That's too bad. I was hoping for recognition not this weird folder structure which is confusing to maintain.

**Comment by ltGuillaume** [comment]
Reading ID3 tags would require a lot of time loading the folder, or a database. I'm not going to do that. I admit that the folder structure is a subjective thing for everyone. If you have a specific folder structure yourself, I could have a look if I can change the related functions for you. If you have no specific folder structure, then I'm afraid you should try implementing ID3 yourself, or find someone else to give that a try. Some design ideas have been influenced by https://github.com/GM-Script-Writer-62850/HTML5-Music-Player. This player **does** support ID3 tags, but if you want the entire tree structure to be based on the ID3 tags, then this player isn't gonna cut it for you, either.

**Comment by Invictaz** [comment]
@ltGuillaume I have that player also and I cannot get the ID3 tags to work. Playlist.php is correctly linked to getid3.php so I don't get where the problem is. However, I might switch fully since your player does not work on IE11. Some users of my site still use that.

**Comment by ltGuillaume** [comment]
Ah that's too bad. I haven't tried ID3 with that player either, but you could ask the author for help, he's cool.

As for IE11, I sincerely hope these users - for their own good - won't use it for their daily browsing...

**Comment by ltGuillaume** [comment]
> @ltGuillaume That's too bad. I was hoping for recognition not this weird folder structure which is confusing to maintain.

@Invictaz You can define your own weird folder structure now with these changes: https://github.com/ltGuillaume/MusicFolderPlayer/tree/regexp In `music.ini`, you can define it in the variable `pathexp`.

Still in the testing phase.
