### ISSUE TITLE
Files don't play if there is a % in the folder path.

### ISSUE THREAD

**Issue by skalez** [ltGuillaume/MusicFolderPlayer#50]
I noticed that if there is a % in the folder name or file name then the audio file does not play.  When the file is played, the http get request includes % rather than the url encode %25 and the server can't find the file.

**Comment by ltGuillaume** [comment]
Thanks for reporting, should be fixed now!

**Comment by skalez** [comment]
Thanks for the quick reply.  Unfortunately I haven't been able to get the page to load using this newest version of music.js file from github.  I have manually changed the code on my local music.js file to include "%" and it works (line 603).

**Comment by ltGuillaume** [comment]
So there's a bug in the current commit? Could you tell me what's in the browser console?
