### ISSUE TITLE
Error im music.js

### ISSUE THREAD

**Issue by askurashev** [ltGuillaume/MusicFolderPlayer#53]
Hello.
I get white page and error in Chrome Console:
```
music.js:106 Uncaught TypeError: pathexp.replace is not a function
    at HTMLScriptElement.lib.onload (music.js:106:21)
lib.onload @ music.js:106
Объект load (асинхронный)
init @ music.js:104
onload @ (индекс):13
```

**Comment by ltGuillaume** [comment]
Hi, I can't reproduce this (without more info). Do you have your own `music.ini`? Can you post the contents here?

**Comment by ltGuillaume** [comment]
@askurashev MFP tries to write a cached version of the library structure into `music.pls/library.json` if you have set the cache to enabled. This fails if you haven't set the proper permissions to the folder MFP is in, or the `music.pls` folder.

So, I figured out you must have the setting `cache = 1` in `music.ini` and not have given the playlist folder (specified by `playlistdir` (by default `music.pls`) proper write permissions.
