### ISSUE TITLE
  "Copy Song Link Clipboard" without feedback.

### ISSUE THREAD

**Issue by Lancenas** [ltGuillaume/MusicFolderPlayer#57]
Is it a coding question?When the song is a Chinese file name sharing "Copy Song Link Clipboard" without feedback.

**Comment by ltGuillaume** [comment]
Without feedback? I don't understand what you mean.

**Comment by Lancenas** [comment]
When the song is a Chinese file name, "Copy Song Link Clipboard" failed，Ask for help, I can't find a solution.
Is there a question here?
`function esc(s) {
	return s.replace(/\/+$/, '').replace(/[(\?=&#% ]/g, function(char) { return escape(char) });
}
function escBase64(s) {
	return s.replace(/=+$/, '').replace(/[\/+=]/g, function(char) { return escape(char) });
}`

**Comment by Lancenas** [comment]
> Without feedback? I don't understand what you mean.

When the song is a Chinese file name, "Copy Song Link Clipboard" failed，Ask for help, I can't find a solution.
Is it a problem here?
https://github.com/ltGuillaume/MusicFolderPlayer/blob/2dcb0d355534e664bb6a1e83b1046a6af7222bed/music.js#L629-L635

**Comment by ltGuillaume** [comment]
I don't see any issues in the esc()/escBase64() functions, to be honest, but we could test it.

Try replacing ` 	return s.replace(/\/+$/, '').replace(/[(\?=&#% ]/g, function(char) { return escape(char) }); ` and `return s.replace(/=+$/, '').replace(/[\/+=]/g, function(char) { return escape(char) });` with `return s;` and see what happens.

**Comment by Lancenas** [comment]
> I don't see any issues in the esc()/escBase64() functions, to be honest, but we could test it.
> 
> Try replacing ` return s.replace(/\/+$/, '').replace(/[(\?=&#% ]/g, function(char) { return escape(char) });` and `return s.replace(/=+$/, '').replace(/[\/+=]/g, function(char) { return escape(char) });` with `return s;` and see what happens.

The return message is 
music.mtom.top/:1 Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.
base-loading.js:1          Failed to load resource: the server responded with a status of 404 ()
music.js:217 16:34:29  https://github.com/ltGuillaume/MusicFolderPlayer
music.js:217 16:34:29  Song count: 7318
/library/%E7%BB%8F%E5%85%B8%E7%BA%AF%E9%9F%B3%E4%B9%90/skymusic-%E4%B9%A6%E9%A6%99%E9%9F%B3%E4%B9%90%2010%E5%BC%A0/CD05%20%E8%8A%B1%E9%97%B4%E6%A2%A6%E4%BA%8B/11.%20%E8%8D%B7%E9%A3%8E%E9%80%81%E9%A6%99%E6%B0%94.mp3:1          Failed to load resource: the server responded with a status of 404 ()
music.js:217 DOMException: Failed to load because no supported source was found.
music.js:217 16:34:45  Error: File not found
/library/%E5%8D%8E%E8%AF%AD%E6%AD%8C%E6%9B%B2%E5%90%88%E8%BE%91/%E5%8D%8E%E8%AF%AD%E7%BB%8F%E5%85%B8%E8%80%81%E6%AD%8C%EF%BC%8C%E6%B0%B8%E6%81%92%E4%B8%8D%E6%9C%BD/%E7%BB%99%E4%BD%A0%E4%BB%AC%20-%20%E5%BC%A0%E5%AE%87.mp3:1          Failed to load resource: the server responded with a status of 404 ()
music.js:217 DOMException: Failed to load because no supported source was found.
music.js:217 16:34:46  Error: File not found
/library/%E5%8D%8E%E8%AF%AD%E6%AD%8C%E6%89%8B/%E9%82%93%E4%B8%BD%E5%90%9B-195%E9%A6%96/%E6%99%A8%E5%85%89%E4%B8%8B%E7%9A%84%E6%81%8B%E6%83%85-%E9%82%93%E4%B8%BD%E5%90%9B%20.mp3:1          Failed to load resource: the server responded with a status of 404 ()
music.js:217 DOMException: Failed to load because no supported source was found.
music.js:217 16:34:46  Error: File not found
/library/%E8%AF%84%E4%B9%A6/%E5%B2%B3%E9%A3%9E%E4%BC%A0(%E5%88%98%E5%85%B0%E8%8A%B3)/%E5%88%98%E5%85%B0%E8%8A%B3_%E5%B2%B3%E9%A3%9E%E4%BC%A0/YueFei071.mp3:1          Failed to load resource: the server responded with a status of 404 ()
music.js:217 DOMException: Failed to load because no supported source was found.
music.js:217 16:34:47  Error: File not found
music.js:217 16:35:27  Error: This song is already in the playlist
music.js:865 Uncaught DOMException: Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range.
    at clip (https://music.mtom.top/music.js:865:46)
    at HTMLButtonElement.onclick (https://music.mtom.top/:79:88)
music.js:865 Uncaught DOMException: Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range.
    at clip (https://music.mtom.top/music.js:865:46)
    at HTMLButtonElement.onclick (https://music.mtom.top/:79:88)
music.js:865 Uncaught DOMException: Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range.
    at clip (https://music.mtom.top/music.js:865:46)
    at HTMLButtonElement.onclick (https://music.mtom.top/:85:84)
clip @ music.js:865
onclick @ (index):85
music.js:865 Uncaught DOMException: Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range.
    at clip (https://music.mtom.top/music.js:865:46)
    at HTMLButtonElement.onclick (https://music.mtom.top/:79:88)
clip @ music.js:865
onclick @ (index):79

**Comment by ltGuillaume** [comment]
Great, thanks for the info!

Could you try if the changes from https://github.com/ltGuillaume/MusicFolderPlayer/commit/c622b682a573b0857b1c82839c08dcb0d845091d help?

**Comment by Lancenas** [comment]
> Great, thanks for the info!
> 
> Could you try if the changes from [c622b68](https://github.com/ltGuillaume/MusicFolderPlayer/commit/c622b682a573b0857b1c82839c08dcb0d845091d) help?

Thank you for your timely response!The problem is solved!

**Comment by ltGuillaume** [comment]
Great!
