### ISSUE TITLE
Autoplay support

### ISSUE THREAD

**Issue by Invictaz** [ltGuillaume/MusicFolderPlayer#6]
Is there an option to auto-play when the page music.htm is opened?

**Comment by ltGuillaume** [comment]
Not planned, no. Just press the space bar and it'll start playing. Either way, most browsers will not allow playback anyway without the user pressing a button first.

**Comment by Invictaz** [comment]
There is something like onload autoplay 
https://www.w3schools.com/tags/att_video_autoplay.asp

It's W3 certified and part of the spec. Yes I know this link is for video.

**Comment by ltGuillaume** [comment]
Yeah that won't work in this case. But check the new commit, looks like it's working. Could you please report back after testing? :-)

**Comment by Invictaz** [comment]
@ltGuillaume Will test later, thanks
