### ISSUE TITLE
Theme support

### ISSUE THREAD

**Issue by Invictaz** [ltGuillaume/MusicFolderPlayer#7]
White is quite hard on the eyes, is there an option to have black background with white text?

**Comment by ltGuillaume** [comment]
Perhaps, this will suffice already: at the very bottom of `music.css` add:
```
body, #cover {
	filter: invert(95%);
	background: #222;
}
```

**Comment by ltGuillaume** [comment]
Please check out https://github.com/ltGuillaume/MusicFolderPlayer/commit/9fb00d0e4c2da768d7b261fcd55b740a12b2cd7e and report back to me.

**Comment by ltGuillaume** [comment]
@Invictaz https://github.com/ltGuillaume/MusicFolderPlayer/issues/12#issuecomment-466373354
