### ISSUE TITLE
Disable album art if not found

### ISSUE THREAD

**Issue by Invictaz** [ltGuillaume/MusicFolderPlayer#8]
Is there an option to disable album art cover if not found?

**Comment by ltGuillaume** [comment]
Why? You want to see an empty square? Or you want the folder / title / time to constantly jump left and right, depending on whether there is album art available? ;-)

**Comment by Invictaz** [comment]
@ltGuillaume Permanent disable and replace by a top logo.
Or just an empty tile with a music note and if there IS album art fill the square with the cover.

**Comment by ltGuillaume** [comment]
> Or just an empty tile with a music note and if there IS album art fill the square with the cover.
I'm afraid I can't follow exactly: isn't this already exactly what happens?

**Comment by Invictaz** [comment]
@ltGuillaume Sorry was confused with another player I have running on my site. 
The option to disable it completely, even if it is present.

**Comment by ltGuillaume** [comment]
You could just change
```#cover {
	min-width: 7.25em;
	max-width: 7.25em;
	min-height: 7.25em;
	max-height: 7.25em;
	border: 1px solid #fafafa;
	border-radius: 3px;
	cursor: zoom-in;
}
	#player.zoom > #cover {
		min-width: 300px;
		min-height: 300px;
		max-width: 300px;
		max-height: 300px;
		cursor: zoom-out;
	}
	#player.zoom > #current { max-width: calc(100% - 300px) }
	#player.fullzoom #cover {
		max-width: 100%;
		max-height: 100%;
		margin: 0 auto;
		cursor: zoom-out;
	}```

to
```
#cover { display: none }
```
