### ISSUE TITLE
No volume slider

### ISSUE THREAD

**Issue by Invictaz** [ltGuillaume/MusicFolderPlayer#9]
Some songs appear too loud. There is no volume slider to control this, other than the one from your device.

**Comment by ltGuillaume** [comment]
Yes, I've heard of some issues with playback where there seems to be distortion in the playback. I'm not sure whether a volume slider would do any good there, though: it's the browser's responsibility to play back the audio properly.

Since mobile devices have a volume slider for media and desktop systems also allow to change browser's volume separately, I'm not planning on implementing yet another volume slider (especially since I'm not convinced that it will solve the distortion problem). In fact, the more volume changes between source and output, the more the audio will be negatively influenced.

If you can find anything on the distortion caused by the browser online, please let me know.

**Comment by xRadio-us** [comment]
Sliders take extra screen space. For most people, a simple button or image click
will mostly accomplish the same thing in a smaller space and located anywhere
on the screen that is convenient and uncluttering.

``<IMG <BUTTON <DIV <SPAN etc. -- onClick = "volUp()"``

```
var volX = 10;
function volUp() { audio[current].volume = ( volX = volX + 2  % 11 )           / 10; }
function volDn() { audio[current].volume = ( volX = Math.max( 1 , volX - 3 ) ) / 10; }
```

The above code is to change volume for only the current song.  To make it a global
volume change, in music.js, find function play(index) and then

change ``a.volume =  1;`` to  ``a.volume =  volX / 10;`` [Example]([https://xradio.us/start/dap/)

**Comment by ltGuillaume** [comment]
@xRadio-us Are you sure the math is correct on that?

**Comment by xRadio-us** [comment]
I'm not sure what you mean. I wanted to make sure that volume stayed within about 0.1 to 1 range.
I figure that users will typically want to lower volume quicker than raise it, so volX-up is incremented by 2 and volX-down is incremented by 3. It is very simple but it seems to work for me.

**Comment by xRadio-us** [comment]
Can you point to where I can darken, disable or remove the upper icon in the left outside column? Especially with my dark theme, it seems distracting and unaesthetic. IMO, there is already too much stuff, especially with my quirky volume buttons, in the upper left area. [Example](https://xradio.us/start/dap/) 

I would prefer to move my volume **+** icon to the upper left side corner of the "cover" image but the upper left column icon is just close and too dominant.

**Comment by ltGuillaume** [comment]
music.css: `body > div:before {`

**Comment by ltGuillaume** [comment]
Those volume buttons on your page don't do a thing currently.

**Comment by xRadio-us** [comment]
Works fine in Chrome but I just tried in Firefox and, as you said, the volume buttons are inactive.

**Comment by xRadio-us** [comment]
re: **music.css** - thanks, for now I just covered it

```
<img src="img/one-black.gif" 
     style="z-index:999;position:absolute;top:10px;left:10px;height:20px;width:20px;">

```

**Comment by ltGuillaume** [comment]
So basically you're censoring with a black bar! Like MFP is a bloody criminal! :-P

**Comment by xRadio-us** [comment]
well, more of a black square (as authorized by Mike Pence) ... ;-)

**Comment by ltGuillaume** [comment]
My my... :-P

But seriously though, if you just want the first one to disappear, remove `#player:before { content: "\f153" }` from the CSS.

**Comment by xRadio-us** [comment]
Thanks. BTW, I moved the side icons down slightly to line up better (for me) with the different sections. Is this placement still okay in Waterfox, etc. or is this placement browser dependent?

**Comment by ltGuillaume** [comment]
![image](https://user-images.githubusercontent.com/4777345/53246932-50409880-36b2-11e9-9995-21a86c679c69.png)

**Comment by xRadio-us** [comment]
Thanks again, It looks like I might have to adjust the button font-sizes down slightly to avoid wrapping.,

**Comment by ltGuillaume** [comment]
Guess you'd better remove `text-shadow: .5px .5px #ddd;` from `body > div:before {`, too.

**Comment by xRadio-us** [comment]
I decided to hide Volume Control buttons for phones. Smartphone hardware buttons should be enough.

```
@media screen and (max-width: 600px) {
    ... etc etc etc
    #volControl { display:none }
}
```

Why Firefox does not react to volume buttons - maybe change how `audio[current].volume` is referenced?

**Comment by ltGuillaume** [comment]
Either way, both volUp() and volDn() aren't proper functions. You'll leave the volume at 0.1 minimal and when you press volUp() it won't go back to 1.

Why don't you just use
```
function volUp() {
  audio[current].volume = Math.min(1, audio[current].volume + .1);
  console.log("Volume = "+ audio[current].volume);
}

function volDn() {
  audio[current].volume = Math.max(0, audio[current].volume - .1);
  console.log("Volume = "+ audio[current].volume);
}
```

**Comment by xRadio-us** [comment]
My real world experience in Chrome would suggest that it works just fine and does go back to 1. But thanks, anyway.

**Comment by ltGuillaume** [comment]
Your use of MOD is wrong:
```
volX = 10;
volX = 10
10
( volX = volX + 2  % 11 )
12
( volX = volX + 2  % 11 )
14
```

**Comment by ltGuillaume** [comment]
Also, `( volX = Math.max( 1 , volX - 3 )` will mean it will always stick to 1/10 = 0.1 and never get 0.

**Comment by xRadio-us** [comment]
Yes, I originally tried volX * 1.2 % 11 and the MOD was effective.  When I just plugged in addition instead of multiplication, I neglected to add parentheses. This resulted in MOD taking precedence over addition so that the upward result hit a browser/HTML5 ceiling at 10 (1) and stayed there. That was actually a happy accident that made the effect work as desired despite the error.

**Comment by ltGuillaume** [comment]
Cool! Good luck!

**Comment by xRadio-us** [comment]
I discovered the reason for the "no action" results in Firefox.

To maintain style with the other buttons, I added my volControl button like this:

`<button id="volControl"><img src=X onclick="volDn()"><img src=Y onclick="volUp()"></button>`

Apparently, Firefox does not allow onClick on images within a button.

I changed it to:

`<div id="volControl"><img onclick></div>` and added #volControl on two CSS button entry lines.
